E_Wish/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('auth_app.urls')),
    path('',include('administrator.urls')),
    path('',include('merchant.urls')),
    path('',include('user.urls')),
    path('',include('recipe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('recipeView<id>',views.recipeView, name="recipeView"),    
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index',views.index,name='index'),
    path('about',views.about,name='about'),
    path('profile',views.profile,name='profile'),
    # path('cart',views.cart,name='cart'),
    # path('checkout',views.checkout,name='checkout'),
    path('contact_us',views.contact_us,name='contact_us'),
    path('feedback',views.feedback,name='feedback'),
    path('gallery',views.gallery,name='gallery'),
    # path('my_account',views.my_account,name='my_account'),
    # path('shop_detail',views.shop_detail,name='shop_detail'),
    path('shop',views.shop,name='shop'),
    path('viewProduct/<id>',views.viewProduct,name='viewProduct'),
    #path('back',views.back,name='back'),

    # path('wishlist',views.wishlist,name='wishlist'),
    path('userlogout',views.userlogout,name='userlogout'),
    
    path('add_to_cart/<id>',views.add_to_cart,name="add_to_cart"),
    path('cart', views.cart, name = 'cart'),

    path('changePassword',views.changePassword,name='changePassword'),
    path('user_change_password',views.user_change_password,name='user_change_password'),
    
    path('remove_cart<id>', views.remove_cart, name="remove_cart"),
    # path('checkout', views.checkout, name = 'checkout'),
    # path('updatecart', views.updateCart, name = 'updatecart'),
    # path('updatequantity', views.updateQuantity, name = 'updatequantity'),
    
    #billing-------------------------------------------------------------------------------------
    
    path('buy_now', views.buy_now, name="buy_now"),
    path('billHistory',views.billHistory,name="billHistory"),
    path('billDetails<id>',views.billDetails,name="billDetails"),
     
]

recipe/models.py
from django.db import models
from merchant.models import product
# Create your models here.
# # recipe

class Recipe(models.Model):
    recipe_id = models.AutoField(primary_key=True)
    recipe_name = models.CharField(max_length=255)
    recipeDescription = models.TextField(max_length=255)
    def _str_(self):
        return self.recipe_name

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(product, on_delete=models.CASCADE)
    amount = models.CharField(max_length=30)
    unit = models.CharField(max_length=20)

    class Meta:
        unique_together = ('recipe', 'ingredient')

    def _str_(self):
        return f"{self.amount} {self.unit} of {self.ingredient} for {self.recipe}"

recipe/forms.py
from django import forms  
#from django.contrib.auth.models import UserCreationForm
#from django.db import forms

from recipe.models import RecipeIngredient


class RecipeIngredientForm(forms.ModelForm):  
    class Meta:  
        model = RecipeIngredient
        fields = ('recipe','ingredient','amount','unit')

recipe/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from user.models import Bill, BillItems
from .models import Recipe, RecipeIngredient
from django.db.models import Q

def recipeView(request,id):
    # return HttpResponse(id)
    # billId = Bill.objects.get(BillId=billId)
    bill_items = BillItems.objects.filter(Bill_id_id=id)
    products = [item.productId for item in bill_items]
    
    recipes = Recipe.objects.filter(
        Q(recipeingredient__ingredient__in=products)
    ).distinct()

    context = {'recipes': recipes, 'id': id}
    return render(request, 'recipeView.html', context)    

recipe/templates/recipeView.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Recipe View</title>
      <link rel="stylesheet" href="static/css/index.css">
  </head>
  <style>
    table {
        width: 50%;
        border-collapse: collapse;
        margin: 0 auto;
      }
      
    th,td{
      border-bottom: 1px solid #ddd;
      text-align:center;
    }
    th{
      background-color: #04aa6d;
      height : 50px;
    }
    td img{
      margin-left:0px;
    }
    .p input{
      width:80px;
      text-align:center;
      border:none;
      font-size:20px;
      font-weight:bold;
    }
    
    .disabled-btn {
        background-color: grey;
    }
  </style>

<body>
    {% if messages %}
      {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
      {% endfor %}
    {% endif %}

    <!-- Start Main Top -->
    {% include 'header.html' %}
    <!-- End Main Top -->
    <br><br><br><br><br>

    {% if recipes %}
    <table>
        <thead>
            <tr>
                <th>Recipe Name</th>
                <th>Description</th>
                <th>Ingredients</th>
                <th>Quantity</th>
                <th>Unit</th>
            </tr>
        </thead>
        <tbody>
            {% for recipe in recipes %}
                <tr>
                    <td>{{ recipe.recipe_name }}</td>
                    <td>{{ recipe.recipeDescription }}</td>
                    <td>
                        <ul>
                            {% for ingredient in recipe.recipeingredient_set.all %}
                                <li>{{ ingredient.ingredient.productName }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            {% for ingredient in recipe.recipeingredient_set.all %}
                                <li>{{ ingredient.amount }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            {% for ingredient in recipe.recipeingredient_set.all %}
                                <li>{{ ingredient.unit }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">No recommended recipes found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No recipes found.</p>
{% endif %}


    <br><br><br><br><br>

</body>
</html>